[package]
name = "backup"
version = "0.0.1"
edition = "2018"
publish = false

[[test]]
name = "integrations"
path = "tests/integrations/mod.rs"

[dependencies]
crc64fast = "0.1"
engine = { path = "../engine" }
engine_rocks = { path = "../engine_rocks" }
engine_traits = { path = "../engine_traits" }
external_storage = { path = "../external_storage" }
failure = "0.1"
futures = "0.1"
grpcio = { version = "0.5.0-alpha.5", features = [ "openssl-vendored" ], default-features = false }
hex = "0.3"
keys = { path = "../keys" }
txn_types = { path = "../txn_types" }
kvproto = { git = "https://github.com/pingcap/kvproto.git", default-features = false }
lazy_static = "1.3"
protobuf = "2.8"
raft = { version = "0.6.0-alpha", default-features = false }
serde = "1.0"
serde_derive = "1.0"
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
# better to not use slog-global, but pass in the logger
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "0e23a5baff302a9d7bccd85f8f31e43339c2f2c1" }
tempfile = "3.0"
tidb_query = { path = "../tidb_query" }
tikv = { path = "../../", default-features = false }
tikv_alloc = { path = "../tikv_alloc" }
tikv_util = { path = "../tikv_util" }
tokio-threadpool = "0.1"
url = "2.0"

[dependencies.prometheus]
git = "https://github.com/pingcap/rust-prometheus.git"
rev = "b668f3911d6569de2e1e8b2672fccec1cc8298be"
default-features = false
features = ["nightly", "push", "process"]

[dev-dependencies]
rand = "0.7"
test_util = { path = "../test_util" }
test_raftstore = { path = "../test_raftstore" }
uuid = { version = "0.7", features = [ "serde", "v4" ] }

[features]
protobuf-codec = ["kvproto/protobuf-codec", "external_storage/protobuf-codec"]
prost-codec = ["kvproto/prost-codec", "external_storage/prost-codec"]
