[package]
name = "sst_importer"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
crc32fast = "1.2"
engine_traits = { path = "../engine_traits" }
external_storage = { path = "../external_storage" }
futures = "0.1"
grpcio = { version = "0.5.0-alpha.5", features = [ "openssl-vendored" ], default-features = false }
hex = "0.3"
keys = { path = "../keys" }
kvproto = { git = "https://github.com/pingcap/kvproto.git", default-features = false }
lazy_static = "1.3"
quick-error = "1.2.2"
serde = "1.0"
serde_derive = "1.0"
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "0e23a5baff302a9d7bccd85f8f31e43339c2f2c1" }
tikv_alloc = { path = "../tikv_alloc", default-features = false }
tokio-sync = "0.1.7"
uuid = { version = "0.7", features = [ "serde", "v4" ] }

[dependencies.prometheus]
git = "https://github.com/pingcap/rust-prometheus.git"
rev = "d919ccd35976b9b84b8d03c07138c1cc05a36087"
default-features = false

[dev-dependencies]
tempfile = "3.0"
test_sst_importer = { path = "../test_sst_importer" }

[features]
protobuf-codec = ["kvproto/protobuf-codec", "external_storage/protobuf-codec"]
prost-codec = ["kvproto/prost-codec", "external_storage/prost-codec"]
