[package]
name = "tikv_util"
version = "0.1.0"
edition = "2018"
publish = false

[features]
failpoints = ["fail/failpoints"]
prost-codec = ["prost"]

[dependencies]
backtrace = "0.3.9"
byteorder = "1.2"
configuration = { path = "../configuration" }
chrono = "0.4"
coarsetime = "0.1"
crc32fast = "1.2"
crossbeam = "0.7.2"
fail = "0.3"
futures = "0.1"
futures-cpupool = "0.1"
fxhash = "0.2.1"
grpcio = { version = "0.5.0-alpha.5", features = [ "openssl-vendored" ], default-features = false }
hex = "0.3"
lazy_static = "1.3"
libc = "0.2"
log = { version = "0.4", features = ["max_level_trace", "release_max_level_debug"] }
openssl = { version = "0.10" }
prost = { version = "0.5", optional = true }
protobuf = "2"
quick-error = "1.2.2"
raft = { version = "0.6.0-alpha", default-features = false }
rand = "0.7"
regex = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
slog-async = "2.3"
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "0e23a5baff302a9d7bccd85f8f31e43339c2f2c1" }
slog-term = "2.4"
tempfile = "3.0"
tikv_alloc = { path = "../tikv_alloc", default-features = false }
time = "0.1"
tokio-core = "0.1"
tokio-executor = "0.1"
tokio-sync = "0.1.7"
tokio-threadpool = "0.1.13"
tokio-timer = "0.2"
toml = "0.4"
url = "2"
utime = "0.2"
zeroize = { version = "0.10", features = [ "alloc" ] }

[dependencies.prometheus]
git = "https://github.com/pingcap/rust-prometheus.git"
rev = "d919ccd35976b9b84b8d03c07138c1cc05a36087"
features = ["nightly", "push", "process"]

[dependencies.prometheus-static-metric]
git = "https://github.com/pingcap/rust-prometheus.git"
rev = "d919ccd35976b9b84b8d03c07138c1cc05a36087"

[target.'cfg(target_os = "linux")'.dependencies]
procinfo = { git = "https://github.com/tikv/procinfo-rs" }

[dev-dependencies]
panic_hook = { path = "../panic_hook" }

