[package]
name = "engine_rocks"
version = "0.0.1"
edition = "2018"
publish = false

[features]
jemalloc = ["rocksdb/jemalloc"]
portable = ["rocksdb/portable"]
sse = ["rocksdb/sse"]

[dependencies]
engine = { path = "../engine" }
engine_traits = { path = "../engine_traits" }
hex = "0.3"
kvproto = { git = "https://github.com/pingcap/kvproto.git", default-features = false }
lazy_static = "1.3"
protobuf = "2"
quick-error = "1.2.2"
raft = { version = "0.6.0-alpha", default-features = false }
serde = "1.0"
serde_derive = "1.0"
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "0e23a5baff302a9d7bccd85f8f31e43339c2f2c1" }
static_assertions = "1.1.0"
sysinfo = { git = "https://github.com/tikv/sysinfo.git", branch = "tikv"}
tikv_alloc = { path = "../tikv_alloc" }
tikv_util = { path = "../tikv_util" }
time = "0.1"
toml = "0.4"

[dependencies.prometheus]
git = "https://github.com/pingcap/rust-prometheus.git"
rev = "b668f3911d6569de2e1e8b2672fccec1cc8298be"
features = ["nightly", "push", "process"]

[dependencies.rocksdb]
git = "https://github.com/pingcap/rust-rocksdb.git"
package = "rocksdb"

[dev-dependencies]
tempfile = "3.0"
