[package]
name = "test_storage"
version = "0.0.1"
edition = "2018"
publish = false

[dependencies]
futures = "0.1"
keys = { path = "../keys" }
txn_types = { path = "../txn_types" }
kvproto = { git = "https://github.com/pingcap/kvproto.git", default-features = false }
test_raftstore = { path = "../test_raftstore" }
tikv = { path = "../../", default-features = false }
tikv_util = { path = "../tikv_util" }
