[package]
name = "test_coprocessor"
version = "0.0.1"
edition = "2018"
publish = false

[features]
prost-codec = ["prost"]

[dependencies]
futures = "0.1"
keys = { path = "../keys" }
txn_types = { path = "../txn_types" }
kvproto = { git = "https://github.com/pingcap/kvproto.git", default-features = false }
prost = { version = "0.5", optional = true }
protobuf = "2"
test_storage = { path = "../test_storage" }
tidb_query = { path = "../tidb_query" }
tikv = { path = "../../", default-features = false}
tikv_util = { path = "../tikv_util" }
tipb = { git = "https://github.com/pingcap/tipb.git", default-features = false }
